name: Main build

on:
  push:
    branches: 'master'
  pull_request:
    branches: '*'

jobs:
  validation:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Gradle wrapper validation
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    runs-on: ${{ matrix.os }}-latest
    needs: validation
    timeout-minutes: 15
    strategy:
      matrix:
        java: [ 8, 11, 16 ]
        os: [ubuntu, windows, macos]
    name: with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Gradle build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: --refresh-dependencies --stacktrace --scan clean build
