name: Main build

on:
  push:
    branches: 'master'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 15
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 11, 14 ]
        os: [ubuntu, windows, macos]
    name: with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up java
        uses: actions/setup-java@v2.3.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: 'gradle'
      - name: Gradle build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: --refresh-dependencies --stacktrace --scan clean build

  buildDone:
    name: buildOk
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: buildOk
        run: echo 'all builds passed'
